In [3]:
#importing a module
import math as m
m.sqrt(16)

4.0

In [4]:
#Python list a generally very slow and are mutable so they are not compact i.e they can hold any type of value
#So for this we will use numpy
#It will Hold Only same type of Data and is also very fast as mostly codes are written in C.




In [22]:
#how to create numpy arrays

import numpy as np
l = [2,3,"34"]
np.array(l) #This will convert every element to string
print(l)

l = [2,3,5]
np.array(l)

#Helper Functions

#Creating 1D array of zeros and ones
z = np.zeros(10)
o = np.ones(10)
print(z)#By Default all values are of Float type
print(o)

z = np.zeros(10,int) #Covert all elements to integer
o = np.ones(10,str) #Convert all element to string
print(z)
print(o)

#Creating Multi-Dimensional array of zeros and ones
#pass a tuple

#2D
z = np.zeros((5,5))
o = np.ones((5,5))
print(z)#By Default all values are of Float type
print(o)

z = np.zeros((5,5),int) #Covert all elements to integer
o = np.ones((5,5),str) #Convert all element to string
print(z)
print(o)


# nD
print()
print("Multi Dimensional Array",end="\n\n")
z = np.zeros((3,5,5)) #3 2D array of 5x5
o = np.ones((3,5,5))
print(z)#By Default all values are of Float type
print(o)

z = np.zeros((3,5,5),int) #Covert all elements to integer
o = np.ones((3,5,5),str) #Convert all element to string
print(z)
print(o)


[2, 3, '34']
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 0 0 0 0 0 0 0 0 0]
['1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']]

Multi Dimensional Array

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1.

In [34]:
#Accessing Elements
print("Shape :",o.shape) #Gives Size of matrix
print("Data Type :",o.dtype) 
a = np.array([[1,2,3],[4,5,6]])
print(a[0]) #0th row
print(a[:,0]) #0th column

np.arange(11) 

Shape : (3, 5, 5)
Data Type : <U1
[1 2 3]
[1 4]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])